CREATE OR REPLACE VIEW VIEW_USERPERMISSIONS AS
SELECT T.USR_ID
      ,T.USR_DISCORD_NAME
	  ,T.USR_FRIENDLY_NAME
	  ,T.USR_CLIENT_ID
	  ,T.ROLE_ID
	  ,T.ROLE_NAME
	  ,T.PERM_ID
	  ,T.PERM_NAME
	  ,T.PERM_TXT
FROM (WITH CTE_USRS AS
		  (SELECT U.ID                AS `USR_ID`
				 ,U.DISCORD_NAME      AS USR_DISCORD_NAME
				 ,NVL(U.FRIENDLY_NAME,
                      U.DISCORD_NAME) AS USR_FRIENDLY_NAME
				 ,U.CLIENTID          AS USR_CLIENT_ID
				 ,U.ROLEID            AS USR_ROLE_ID
		  FROM USERS U),
		  CTE_ROLES AS
		  (SELECT R.ID                   AS ROLE_ID
				 ,R.ROLENAME             AS ROLE_NAME
				 ,NVL(P.ID, '0')         AS PERM_ID
				 ,NVL(P.PERM_NAME, '--') AS PERM_NAME
				 ,NVL(P.PERM_TXT,  '--') AS PERM_TXT
		   FROM ROLES R
		   LEFT OUTER JOIN ROLE_PERMS RP
		       ON RP.ROLEID = R.ID
		   LEFT OUTER JOIN `PERMISSIONS` P
		       ON P.ID = RP.PERMID)
	  SELECT *
	  FROM CTE_USRS U
	  JOIN CTE_ROLES R
	      ON R.ROLE_ID = U.USR_ROLE_ID) T;